apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
{{- with .Values.global.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
